config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :categories
  devise_for :users
  resources :orders
  resources :members
  resources :users
  resources :items

  root 'orders#index'
  get 'renew/:id' => 'orders#renew'
  get 'return/:id' => 'orders#disable'
  get 'past_orders' => 'orders#old'
  get 'report'=> 'report#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b>
    0.1
  </div>
  <a href="#">Developed by <strong>Prashant Shrestha</strong></a>.
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <a href="<%= root_url %>" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini">
      <b>G</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg">
      <b>Goddam</b>
    </span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
  </nav>
</header>
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag("user2-160x160.jpg", class: "img-circle") %>
      </div>
      <div class="pull-left info">
      <% if current_user.admin %>
        <p><%= current_user.name %>(Admin)</p>
       <% else %>
          <p><%= current_user.name %>(Customer)</p>
      <% end %>

        <a href="<%= edit_user_path(current_user.id) %>">
          <i class="fa fa-edit"></i>
          Edit Profile</a>
        <a href="">
          <%= link_to destroy_user_session_path, method: :delete  do %>
          <i class="fa fa-sign-out"></i>Log Out
        <% end %>
        </a>
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>
      <li>
        <a href="<%= root_url %>">
          <i class="fa fa-home"></i>
          <span>Home Page</span>
        </a>
      </li>
      <li>
        <a href="<%= items_path %>">
          <i class="fa fa-search"></i>
          <span>Check Inventory</span>
        </a>
      </li>
      <li>
        <a href="<%= past_orders_path %>">
          <i class="fa fa-history"></i>
          <span>Past Orders</span>
        </a>
      </li>
      <li>
      <a href=" <%= new_category_path %>">
        <i class="fa fa-plus"></i>
        <span>Add Category</span>
      </a>
    </li>
      <li>
        <a href=" <%= new_item_path %>">
          <i class="fa fa-plus"></i>
          <span>Add Item</span>
        </a>
      </li>
      <li>
        <a href="<%= new_user_path %>">
          <i class="fa fa-user-plus"></i>
          <span>Add Member</span>
        </a>
      </li>
      <li>
        <a href="/report">
        <i class="fa fa-history"></i>
          <span>Report</span>
        </a>
      </li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/_notifications.html.erb
<% unless flash.empty? %>
<script type="text/javascript">
  $(document).ready(function () {
    toastr.options = {
      "closeButton": false,
      "debug": true,
      "newestOnTop": false,
      "progressBar": false,
      "positionClass": "toast-top-right",
      "preventDuplicates": false,
      "onclick": null,
      "showDuration": "300",
      "hideDuration": "500",
      "timeOut": "1500",
      "extendedTimeOut": "500",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
    }
    <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'success') %>
    toastr['<%= type %>']('<%= f[1] %>');
    <% end %>
  });
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Godam</title>
    <%= csrf_meta_tags %>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
    <%= stylesheet_link_tag "toastr.css" %>
    <%= stylesheet_link_tag "AdminLTE.min.css" %>
    <%= stylesheet_link_tag "admin-lte-all-skins.min.css" %>
    <%= stylesheet_link_tag "blue.css" %>
    <%= stylesheet_link_tag "dataTables.bootstrap.css" %>
    <%= stylesheet_link_tag "datepicker3.css" %>

    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css" %>
    <%= javascript_include_tag "https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"%>
    <%= javascript_include_tag "toastr.min.js" %>
    <%= javascript_include_tag "bootstrap3-wysihtml5.all.min.js"%>
    <%= javascript_include_tag "jquery.dataTables.min.js"%>
    <%= javascript_include_tag "dataTables.bootstrap.min.js"%>
    <%= javascript_include_tag "jquery.slimscroll.min.js"%>
    <%= javascript_include_tag "fastclick.js"%>
    <%= javascript_include_tag "admin-lte-app.min.js"%>
    <%= javascript_include_tag "icheck.min.js"%>
    <%= javascript_include_tag "bootstrap-datepicker.js"%>

  </head>
    <%= render 'layouts/notifications' %>
    <%= yield %>
</html>